version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: gamestore-backend
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: gamestore-frontend
    ports:
      - "8080:80"

volumes:
  mongo_data:
